on load:
	set {whitelist} to false if {whitelist} isn't set

on connect:
	{whitelist} is true
	player doesn't have permission "whitelist.bypass"
	kick player due to "&cNo, defunding is a private server. You cannot join."
	
command /whitelist <boolean>:
	permission: staff.whitelist
	usage: &cCorrect usage: /whitelist <true/false>
	trigger:
		if arg 1 is true:
			if {whitelist} is true:
				send "&cWhitelist is already enabled, nothing has been changed." to sender
				stop
			set {whitelist} to true
			send "&aEnabled &7whitelist."
		else if arg 1 is false:
			if {whitelist} is false:
				send "&cWhitelist is already disabled, nothing has been changed." to sender
				stop
			set {whitelist} to false
			send "&cDisabled &7whitelist."