on join:
    set join message to "&7&o%player% &7&ojoined."
    
on quit:
    set quit message to "&7&o%player% &7&oleft."

on chat:
    event isn't cancelled
    set {_c} to "&7" if player's group is "default"
    set {_c} to "&f" if player's group isn't "default"
    set the chat format to "%player's prefix%%player%%{_c}%: %{_c}%%message%"
    
command /spawn:
    trigger:
        teleport player to {location::spawn}